### ISSUE TITLE
README and RELEASE Notes

### ISSUE THREAD

**Issue by granthbr** [jbetanzos/mulesoft-sf-twitter-mysql-integration#1]
Could you add a detailed README and Release note file? Not that it is critical but we should start following the process as a regular starting point for all processes.

**Comment by granthbr** [comment]
To be more specific, a description on the project, the prerequisites for that project, project specific settings (JVM version, Mule version, Mule type: EE or CE) need to be specified in the README. Also, mentioning next steps towards the bottom of the file.

**Comment by jbetanzos** [comment]
Ready
